import { useMemo, useState } from 'react';
import { geoNaturalEarth1, geoPath, geoGraticule10 } from 'd3-geo';
import { Mountain, Globe2, SlidersHorizontal, ClipboardList, Bookmark, ArrowUpRight, ArrowRight, Search, Play, Download, Upload, Plus, Minus, RotateCcw, Info, Trash2, Copy, Printer, X } from 'lucide-react';
import catalog from './data/volcanoes.json';
import world from './data/world.json';
import { searchVolcanoes, volcanoContext } from './volcanoInfo';
import { defaults, runSimulation, signalSpecs, settingSpecs, actions, parseScenario, type Volcano, type SavedScenario } from './model';

const volcanoes=catalog.volcanoes as Volcano[];
const ids=new Set(volcanoes.map(v=>v.id));
const countries=[...new Set(volcanoes.map(v=>v.country))].sort();
const projection=geoNaturalEarth1().fitExtent([[20,35],[960,495]],world as never);
const path=geoPath(projection);
const landPath=path(world as never)||'';
const graticule=path(geoGraticule10())||'';
const initial=volcanoes.find(v=>v.name==='Merapi')||volcanoes[0];
function readSaves():SavedScenario[]{try {const raw=JSON.parse(localStorage.getItem('ashline-scenarios')||'[]');return Array.isArray(raw)?raw.map(x=>parseScenario(x,ids)):[];}catch{return [];}}
const dateLabel=(n:number|null)=>n===null?'Unknown':n<0?`${Math.abs(n).toLocaleString()} BCE`:`${n} CE`;
function App(){
 const [view,setView]=useState('Atlas');const [mode,setMode]=useState('Operations');
 const [selected,setSelected]=useState(initial);const [signals,setSignals]=useState(defaults(initial).signals);const [settings,setSettings]=useState(defaults(initial).settings);
 const [page,setPage]=useState(0);const [query,setQuery]=useState('');const [country,setCountry]=useState('');const [zoom,setZoom]=useState(1);
 const [saved,setSaved]=useState(readSaves);const [notes,setNotes]=useState('');const [notice,setNotice]=useState('');const [checked,setChecked]=useState<string[]>([]);const [method,setMethod]=useState(false);
 const result=useMemo(()=>runSimulation(settings,signals,selected),[settings,signals,selected]);
 const filtered=useMemo(()=>searchVolcanoes(volcanoes,query,country),[query,country]);
 const context=volcanoContext(selected);
 function select(v:Volcano){setSelected(v);const d=defaults(v);setSignals(d.signals);setSettings(d.settings);setChecked([]);setNotes('');setNotice('');}
 function snapshot():SavedScenario {const now=new Date().toISOString();return {version:1,id:crypto.randomUUID(),name:`${selected.name} · VEI ${settings.vei}`,volcanoId:selected.id,signals,settings,notes,created:now,updated:now};}
 function persist(next:SavedScenario[]){try{localStorage.setItem('ashline-scenarios',JSON.stringify(next));setSaved(next);return true;}catch{setNotice('Browser storage is full or unavailable. Export JSON to keep this scenario.');return false;}}
 function save(){if(persist([...saved,snapshot()]))setNotice('Scenario saved on this device.');}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`ashline-${selected.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function load(x:SavedScenario){setSelected(volcanoes.find(v=>v.id===x.volcanoId)!);setSettings(x.settings);setSignals(x.signals);setNotes(x.notes);setChecked([]);setView('Simulator');setNotice(`Loaded ${x.name}.`);}
 async function upload(file?:File){if(!file)return;try{if(file.size>100000)throw new Error('File too large. Choose an Ashline scenario under 100 KB.');const x=parseScenario(JSON.parse(await file.text()),ids);load(x);setNotice('Imported scenario. Save to keep it on this device.');}catch(e){setNotice(e instanceof Error?e.message:'Unable to import scenario.');}}
 const location=projection([selected.lon,selected.lat])||[490,260];
 return <div className="app">
  <a className="skip" href="#main">Skip to content</a>
  <aside className="sidebar">
   <a className="brand" href="#" onClick={e=>{e.preventDefault();setView('Atlas');}}><img src={`${import.meta.env.BASE_URL}ashline.svg`} alt="" width="29" height="29"/><span>ashline<span className="brand-dot">.</span></span></a>
   <p className="brand-caption">VOLCANO RISK & READINESS</p>
   <div className="workspace"><span className="workspace-symbol"><Globe2 size={18}/></span><div>Global workspace<small>Training environment</small></div></div>
   <nav aria-label="Main navigation">{[{name:'Atlas',label:'Volcano atlas',icon:Globe2},{name:'Simulator',label:'Scenario simulator',icon:SlidersHorizontal},{name:'Response',label:'Response plan',icon:ClipboardList},{name:'Saved',label:'Saved scenarios',icon:Bookmark}].map(({name,label,icon:Icon})=><button key={name} className={view===name?'nav active':'nav'} onClick={()=>setView(name)}><Icon size={18}/>{label}{name==='Saved'&&<span className="nav-count">{saved.length}</span>}</button>)}</nav>
   <div className="sidebar-bottom"><div className="training-mark"><span/> DEMO / NOT LIVE</div><p>Practice decisions.<br/>Build readiness.</p><button className="text-button" onClick={()=>setMethod(!method)}><Info size={16}/> Model & data notes</button><small>Smithsonian GVP catalog<br/>{catalog.count.toLocaleString()} volcanoes · Global coverage</small></div>
  </aside>
  <div className="shell"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> <strong>{view==='Atlas'?'Volcano atlas':view==='Simulator'?'Scenario simulator':view==='Response'?'Response plan':'Saved scenarios'}</strong></div><div className="mode-switch" aria-label="Audience view">{['Operations','Community'].map(m=><button key={m} aria-pressed={mode===m} className={mode===m?'selected':''} onClick={()=>setMode(m)}>{m}</button>)}</div><span className="avatar" aria-label="Training workspace">AT</span></header>
   <main id="main"><div className="page-heading"><div><h1>{view==='Atlas'?'A world of volcanoes.':view==='Simulator'?'Explore what could happen.':view==='Response'?'Turn insight into readiness.':'Your scenario library.'}</h1><p>{view==='Atlas'?'Explore the landscape. Understand the hazards. Plan ahead.':view==='Simulator'?'Change the conditions. See how the training scenario responds.':view==='Response'?'A shared starting point for safer, coordinated decisions.':'Saved on this device. Ready for the next exercise.'}</p></div><span className="training-badge"><span/> TRAINING MODE</span></div>
   <div className="demo-note"><Info size={16}/><span>Real volcanoes. Simulated conditions. <strong>This is a training tool, not a forecast or official alert.</strong></span><button onClick={()=>setMethod(!method)}>How it works <ArrowUpRight size={14}/></button></div>
   {notice&&<div className="notice" role="status">{notice}<button aria-label="Dismiss message" onClick={()=>setNotice('')}><X size={16}/></button></div>}
   {method&&<section className="method"><h2>Understand the model</h2><p>Eruptions cannot currently be prevented. Monitoring, preparedness, and official evacuation decisions can reduce loss. All signals here are synthetic and must never be interpreted as observations.</p><p>Unrest index: 25% seismicity + 25% tremor + 20% uplift + 20% SO₂ + 10% thermal anomaly, each normalized to its slider range. Rainfall affects lahar reach only. The sensitivity range is an illustrative score range, not a statistical confidence interval.</p><p>Hazard distances use a simple VEI scale, type factor, duration, wind and rainfall. No terrain, atmospheric dispersion, local hydrology, population, evacuation routing or validation is included. Submarine hazards and tsunamis are outside this model. A low score does not establish safety.</p><p>Catalog: <a href="https://volcano.si.edu/" target="_blank" rel="noreferrer">Smithsonian Global Volcanism Program</a>, complete Holocene WFS snapshot ({catalog.count} records), retrieved {catalog.retrieved}. Catalog membership and metadata may change. Geography: Natural Earth 110m land, public domain. <a href={selected.url} target="_blank" rel="noreferrer">Selected volcano source <ArrowUpRight size={12}/></a></p></section>}
   {view==='Atlas'&&<>
    <div className="atlas-layout"><section className="map-panel"><div className="panel-heading"><h2>Global volcano atlas</h2><span>{filtered.length.toLocaleString()} volcanoes</span></div>
     <div className="world-map"><svg viewBox="0 0 980 530" aria-label="Global volcano map. Searchable volcano list follows." role="img"><rect width="980" height="530" fill="#e7edeb"/><g transform={`translate(${490-490*zoom},${265-265*zoom}) scale(${zoom})`}><path d={graticule} fill="none" stroke="#d2dcd8" strokeWidth=".6"/><path d={landPath} fill="#fbfcf8" stroke="#c8d4cd" strokeWidth=".7"/>{filtered.map(v=>{const p=projection([v.lon,v.lat]);return p&&<circle key={v.id} cx={p[0]} cy={p[1]} r={v.id===selected.id?5:2.7} fill={v.id===selected.id?'#bc4c32':'#779b88'} stroke="#f7faf6" strokeWidth=".6" onClick={()=>select(v)} className="map-dot"><title>{v.name}, {v.country}</title></circle>})}<circle cx={location[0]} cy={location[1]} r="13" fill="none" stroke="#bc4c32" strokeWidth="1.4"/><path d={`M${location[0]+12},${location[1]-12}l20,-22h100`} stroke="#bc4c32" fill="none"/><text x={location[0]>800?location[0]-100:location[0]+35} y={location[1]-41} fontSize="14" fill="#753923" fontWeight="600">{selected.name}</text></g></svg>
     <div className="map-caption"><span className="map-key"/> Holocene volcano <span className="map-key selected-key"/> Selected</div><div className="map-controls"><button aria-label="Zoom in" disabled={zoom>=2} onClick={()=>setZoom(z=>Math.min(2,z+.25))}><Plus size={17}/></button><button aria-label="Zoom out" disabled={zoom<=1} onClick={()=>setZoom(z=>Math.max(1,z-.25))}><Minus size={17}/></button><button aria-label="Reset map zoom" onClick={()=>setZoom(1)}><RotateCcw size={15}/></button></div></div><div className="map-footer"><span>GLOBAL REFERENCE MAP</span><span>Holocene · approximately the last 11,700 years</span></div>
    </section><section className="dossier"><div className="dossier-top"><Mountain size={24}/></div><h2>{selected.name}</h2><p>{selected.country} <span>· {selected.region}</span></p><dl><div><dt>Volcano type</dt><dd>{selected.type}</dd></div><div><dt>Elevation</dt><dd>{selected.elevation===null?'Unknown':`${selected.elevation.toLocaleString()} m`}</dd></div><div><dt>Last known eruption</dt><dd>{dateLabel(selected.lastEruption)}</dd></div><div><dt>Coordinates</dt><dd>{selected.lat.toFixed(3)}°, {selected.lon.toFixed(3)}°</dd></div></dl><div className="dossier-hint">Start with a synthetic scenario.<br/>Explore hazards at your own pace.</div><button className="primary" onClick={()=>setView('Simulator')}><Play size={15}/> Build a scenario <ArrowRight size={17}/></button><a className="source-link" href={selected.url} target="_blank" rel="noreferrer">View Smithsonian record <ArrowUpRight size={14}/></a></section></div>
    <section className="volcano-information" aria-labelledby="geology-heading">
     <div className="geology"><h2 id="geology-heading">About {selected.name}</h2><p className="information-source">Smithsonian GVP · Catalog snapshot {catalog.retrieved} · Record {selected.id}</p><p>{selected.summary?.trim() || 'No geological summary is available in this catalog snapshot. Open the Smithsonian record for further information.'}</p><a href={selected.url} target="_blank" rel="noreferrer">Read the source record <ArrowUpRight size={14}/></a></div>
     <aside className="volcano-context"><h3>{context.title}</h3><p>{context.text}</p><p><strong>General educational context.</strong> This is not a site-specific hazard assessment.</p><h3>Current activity</h3><p>Not available in this offline catalog. “Last known eruption” is a historical catalog field, not an activity status or an all-clear.</p><a href="https://volcano.si.edu/reports_weekly.cfm" target="_blank" rel="noreferrer">GVP weekly activity reports <ArrowUpRight size={14}/></a><p>Check report dates and the responsible local observatory for current guidance.</p></aside>
    </section>
    <section className="catalog"><div className="catalog-heading"><h2>Find your volcano <span>{catalog.count.toLocaleString()}</span></h2><div className="filters"><label className="search"><Search size={17}/><input aria-label="Search volcanoes" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder="Search name, region, type, geology…"/></label><select aria-label="Filter by country" value={country} onChange={e=>{setCountry(e.target.value);setPage(0);}}><option value="">All countries</option>{countries.map(c=><option key={c}>{c}</option>)}</select></div></div><div className="table-scroll"><table><thead><tr><th>Volcano</th><th>Country</th><th>Type</th><th>Elevation</th><th>Last known eruption</th><th><span className="sr-only">Select</span></th></tr></thead><tbody>{filtered.slice(page*60,(page+1)*60).map(v=><tr key={v.id} className={selected.id===v.id?'selected-row':''}><td><button onClick={()=>select(v)}><Mountain size={16}/>{v.name}</button></td><td>{v.country}</td><td>{v.type}</td><td>{v.elevation===null?'Unknown':`${v.elevation.toLocaleString()} m`}</td><td>{dateLabel(v.lastEruption)}</td><td><button aria-label={`Simulate ${v.name}`} onClick={()=>{select(v);setView('Simulator')}}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>{!filtered.length&&<p className="empty">No volcanoes match. Try another name or clear the country filter.</p>}<div className="catalog-pagination"><p className="table-note" role="status">Showing {filtered.length?page*60+1:0}–{Math.min((page+1)*60,filtered.length)} of {filtered.length.toLocaleString()} matches</p><div><button className="secondary" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous page</button><button className="secondary" disabled={(page+1)*60>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next page</button></div></div></section>
   </>}
   {view==='Simulator'&&<><div className="scenario-bar"><div><Mountain size={20}/><strong>{selected.name}</strong><span>{selected.country} · {result.preset} preset</span></div><button className="secondary" onClick={()=>setView('Atlas')}>Change volcano</button></div>
    {result.unsupported&&<div className="notice">This volcano is submarine or below sea level. Terrestrial envelopes are hypothetical only; underwater processes and tsunamis are not modeled.</div>}
    <div className="simulation-layout"><section className="controls-panel"><h2>{mode==='Operations'?'Scenario conditions':'Try a practice scenario'}</h2><p className="muted">Synthetic inputs · updates immediately</p><h3>Monitoring signals</h3>{signalSpecs.map(spec=><label className="slider" key={spec.key}><span>{spec.label}<output>{signals[spec.key].toLocaleString()} <small>{spec.unit}</small></output></span><input type="range" aria-label={spec.label} min="0" max={spec.max} step={spec.step} value={signals[spec.key]} onChange={e=>setSignals({...signals,[spec.key]:+e.target.value})}/></label>)}<h3>Eruption & weather</h3>{settingSpecs.map(spec=><label className="slider" key={spec.key}><span>{spec.label}<output>{settings[spec.key]} <small>{spec.unit}</small></output></span><input type="range" aria-label={spec.label} min={spec.min} max={spec.max} step={spec.step} value={settings[spec.key]} onChange={e=>setSettings({...settings,[spec.key]:+e.target.value})}/></label>)}<button className="text-button" onClick={()=>{const d=defaults(selected);setSignals(d.signals);setSettings(d.settings)}}><RotateCcw size={14}/> Reset to type preset</button></section>
    <div className="results"><section className="unrest"><div><h2>{result.band}</h2><p>Illustrative unrest index · not eruption probability</p></div><strong>{result.score}<small>/ 100</small></strong><div className="score-track"><span style={{width:`${result.score}%`}}/></div><p>Sensitivity range: {result.low}–{result.high}. No statistical confidence implied.</p></section><section className="hazard-panel"><div className="panel-heading"><h2>Hazard envelope</h2><span>SCHEMATIC · KM</span></div><HazardMap result={result} direction={settings.direction}/><div className="hazard-metrics"><div><i className="ash-key"/><span>Ash downwind reach</span><strong>{result.ash} km</strong></div><div><i className="pdc-key"/><span>Pyroclastic flow radius</span><strong>{result.pdc} km</strong></div><div><i className="lahar-key"/><span>Lahar reach potential</span><strong>{result.lahar} km</strong></div></div><p className="table-note">Hypothetical distances, not mapped boundaries. Lahar direction depends on river channels; no terrain or channels are modeled here.</p></section><div className="next-step"><div><h2>From scenario to action.</h2><p>Build a staged readiness plan for this exercise.</p></div><button className="primary" onClick={()=>setView('Response')}>Prepare response <ArrowRight size={16}/></button></div></div></div>
   </>}
   {view==='Response'&&<><div className="scenario-bar"><div><Mountain size={20}/><strong>{selected.name}</strong><span>VEI {settings.vei} · {result.band} · Training exercise</span></div><button className="secondary" onClick={()=>setView('Simulator')}>Edit scenario</button></div><div className="response-layout"><section className="action-list"><h2>{mode==='Operations'?'Response planning checklist':'Your readiness checklist'}</h2><p className="muted">{mode==='Operations'?'Exercise prompts, not live instructions. Assign roles with your local authority.':'Follow local authorities during an actual event. These are practice prompts.'}</p>{actions.filter(a=>mode==='Operations'||['Community liaison','Public information officer','Field coordinator','Recovery lead'].includes(a.role)).map(a=><label className="action" key={a.title}><input type="checkbox" checked={checked.includes(a.title)} onChange={e=>setChecked(e.target.checked?[...checked,a.title]:checked.filter(t=>t!==a.title))}/><span><small>{a.phase} <span>· {a.role}</span></small><strong>{a.title}</strong><p>{a.text}</p></span></label>)}</section><aside className="brief"><ClipboardList size={28}/><h2>Exercise brief</h2><p>{selected.name}, {selected.country}</p><dl><div><dt>Unrest index</dt><dd>{result.score} / 100</dd></div><div><dt>Ash reach</dt><dd>{result.ash} km</dd></div><div><dt>Pyroclastic flow</dt><dd>{result.pdc} km</dd></div><div><dt>Lahar potential</dt><dd>{result.lahar} km</dd></div></dl><label className="notes">Planning notes<textarea maxLength={5000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Record decisions, contacts, or questions for your exercise…"/></label><button className="primary" onClick={save}><Bookmark size={16}/> Save scenario</button><div className="export-buttons"><button className="secondary" onClick={download}><Download size={15}/> JSON</button><button className="secondary" onClick={()=>window.print()}><Printer size={15}/> Print brief</button></div><small>Checklist completion stays in this session. Settings and notes are saved locally.</small></aside></div></>}
   {view==='Saved'&&<section className="saved-panel"><div className="catalog-heading"><h2>{saved.length} saved {saved.length===1?'scenario':'scenarios'}</h2><label className="secondary upload"><Upload size={15}/> Import JSON<input type="file" accept="application/json,.json" onChange={e=>{void upload(e.target.files?.[0]);e.target.value=''}}/></label></div>{saved.length?saved.map(x=><article className="saved-row" key={x.id}><Bookmark size={21}/><div><h3>{x.name}</h3><p>{new Date(x.created).toLocaleString()} · Saved locally</p></div><button className="secondary" onClick={()=>load(x)}>Open <ArrowRight size={14}/></button><button className="icon-button" aria-label={`Duplicate ${x.name}`} onClick={()=>{persist([...saved,{...x,id:crypto.randomUUID(),name:`${x.name} copy`.slice(0,120),created:new Date().toISOString(),updated:new Date().toISOString()}])}}><Copy size={16}/></button><button className="icon-button" aria-label={`Delete ${x.name}`} onClick={()=>{if(persist(saved.filter(s=>s.id!==x.id)))setNotice('Scenario deleted from this browser. Exported copies are unaffected.')}}><Trash2 size={16}/></button></article>):<div className="empty-library"><Bookmark size={36}/><h2>A place for your next exercise.</h2><p>Build a scenario, then save it from your response plan.</p><button className="primary" onClick={()=>setView('Atlas')}>Explore volcanoes <ArrowRight size={16}/></button></div>}</section>}
   <footer><span><Mountain size={15}/> ASHLINE <span>Build readiness. Reduce loss.</span></span><button className="text-button" onClick={()=>setMethod(!method)}>Data & model limitations <ArrowUpRight size={13}/></button></footer>
   </main>
  </div>
 </div>
}
function HazardMap({result:r,direction}:{result:ReturnType<typeof runSimulation>;direction:number}){
 const extent=Math.max(r.ash*1.12,r.lahar*1.2,r.pdc*1.2,10);const scale=170/extent;
 return <svg className="hazard-map" viewBox="0 0 600 420" role="img" aria-label={`Illustrative hazard distances: ash ${r.ash} kilometers downwind, pyroclastic flow ${r.pdc}, lahar potential ${r.lahar}. North is up.`}><defs><pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M30 0H0V30" fill="none" stroke="#d9e2dc" strokeWidth=".6"/></pattern></defs><rect width="600" height="420" fill="#eef2ed"/><rect width="600" height="420" fill="url(#grid)"/>{[.25,.5,.75,1].map(f=><g key={f}><circle cx="300" cy="210" r={170*f} fill="none" stroke="#b7c8bc" strokeDasharray="3 5"/><text x={305+170*f} y="206" fill="#53695d" fontSize="11">{(extent*f).toFixed(0)}</text></g>)}<ellipse cx="300" cy={210-r.ash*scale/2} rx={r.ash*scale*.22} ry={r.ash*scale/2} transform={`rotate(${direction} 300 210)`} fill="#bd8c4040" stroke="#a17b38"/><circle cx="300" cy="210" r={r.lahar*scale} fill="none" stroke="#487d9a" strokeDasharray="7 5" strokeWidth="2"/><circle cx="300" cy="210" r={r.pdc*scale} fill="#c7533630" stroke="#bd5137" strokeWidth="2"/><path d="M290 217l10-20 10 20z" fill="#294a3b" stroke="#fff"/><path d="M554 67V32m-5 8 5-8 5 8" stroke="#456453" fill="none"/><text x="549" y="23" fill="#456453" fontSize="12">N</text><text x="22" y="390" fill="#53695d" fontSize="12">Relative to volcano summit · schematic only</text></svg>
}
export default App;
